### ISSUE TITLE
UI Recommendation: Preline

### ISSUE THREAD

**Issue by ryanbenson** [genshintools/genshin-feedback#6]
Since it's using Tailwind, I recommend using a UI kit. It'll simplify a lot, so UI decisions can be made around simple things like forms, etc. I recommend Preline: https://preline.co/ - It's free, and high quality.

I can pull together a PR to introduce it, they have Vue integration: https://preline.co/docs/frameworks-vuejs.html

**Comment by genshintools** [comment]
Good idea 👍 that'll simplify some stuff. Go for it and make a PR to pull it in
